[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/[...path]/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173

[build.environment]
  NODE_VERSION = "18"
